version: "3.8"

services:
  photo-stream:
    build: .
    ports:
      - "5500:5500"
    environment:
      PORT: ${PORT}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      SESSION_SECRET: ${SESSION_SECRET}
      THUMB_SIZE: ${THUMB_SIZE}
      THUMB_QUALITY: ${THUMB_QUALITY}
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./public:/app/public
    restart: unless-stopped
